"""empty message

Revision ID: c89c79e3ee95
Revises: 23c7f8015477
Create Date: 2023-12-14 10:27:35.271989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89c79e3ee95'
down_revision = '23c7f8015477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item'], ['id'])

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item')

    # ### end Alembic commands ###
